drivers:
  auth: sample-config/scripts/auth.pm
  filter: sample-config/scripts/filter.pm
listeners:
  socks5:
    log: logs/socks5.log
    sniff:
      incoming: logs/incoming.sniff
      outgoing: logs/outgoing.sniff
    config:
      type: basic
      network: tcp
      address: 127.0.0.1:9050
      filters:
        #inbound: filter
        #outbound: filter
        listen: filter
        accept: filter
    protocol:
      type: socks5
      authentication: auth