version: "3.3"

networks:
  fullproxy:
    external: false

services:
  echo:
    image: hashicorp/http-echo:latest
    container_name: fullproxy-http-echo
    restart: unless-stopped
    networks:
      - fullproxy
    ports:
      - "127.0.0.1:8000:80"
    command: ["-listen", ":80", "-text", "ECHO"]
  sshd:
    build:
      context: sshd
      dockerfile: Dockerfile
    container_name: fullproxy-sshd
    restart: unless-stopped
    networks:
      - fullproxy
    ports:
      - "127.0.0.1:22222:22"