version: "3.3"

networks:
  fullproxy:
    external: false

services:
  echo:
    image: hashicorp/http-echo:latest
    container_name: fullproxy-http-echo
    restart: unless-stopped
    networks:
      - fullproxy
    ports:
      - "127.0.0.1:8000:80"
    command: ["-listen", ":80", "-text", "ECHO"]
  sshd:
    image: panubo/sshd:latest
    container_name: fullproxy-sshd
    restart: unless-stopped
    networks:
      - fullproxy
    ports:
      - "127.0.0.1:2222:22"
    volumes:
      - ./sshd/entrypoint.sh:/etc/entrypoint.d/entrypoint.sh:ro
    environment:
      - SSH_ENABLE_PASSWORD_AUTH=true
      - GATEWAY_PORTS=true
      - TCP_FORWARDING=true
      - SSH_ENABLE_ROOT=true
      - SSH_ENABLE_ROOT_PASSWORD_AUTH=true
