name: Test

on:
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: Clean
        run: go clean && go clean -cache
      - name: Build
        run: go build .
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: Set up docker environment
        run: docker compose up -d
      - name: Clean
        run: go clean && go clean -cache
      - name: Test
        run: go test -p 1 -count 1 -v ./...
      - name: Clean docker environment
        run: docker compose down --rmi all -v --remove-orphans